using System.Collections;
using System.Collections.Generic;
using Beamable.Common.Leaderboards;
using Beamable.Leaderboards;
using Beamable.Common;
using Beamable.Common.Api.Leaderboards;
using Beamable;
using UnityEngine;
using System;
using System.Threading.Tasks;
using Beamable.Common.Content;
using UnityEngine.SocialPlatforms.Impl;
using Beamable.Api.Autogenerated.Models;
using RankEntry = Beamable.Common.Api.Leaderboards.RankEntry;
using LeaderBoardView = Beamable.Common.Api.Leaderboards.LeaderBoardView;
using TMPro;
using UnityEngine.UI;
using Unity.Mathematics;
using Random = UnityEngine.Random;
using PubNubMessaging.Core;
using Beamable.Server.Clients;
using Newtonsoft.Json.Linq;
using Object = UnityEngine.Object;
using System.Linq;
using Beamable.Common.Api;

public class LeaderboardServiceTest : MonoBehaviour
{
    //  Variables/Fields  ---------------------------------------
    [SerializeField] public PetDataRef petDataRef;
    public PetLocalData petLocalRef;

    [SerializeField] public Transform entryContainer;
    [SerializeField] public Transform entryTemplate;
    private List<LeaderboardEntry> leaderboardEntryList;
    private List<Transform> leaderboardEntryTransformList;

    private LeaderboardServiceClient _LeaderboardServiceClient = null;



    //  Unity Methods  --------------------------------

    private async void Awake()
    {
        entryTemplate.gameObject.SetActive(false);
        List<LeaderboardEntry> tempEntries = await TestMicroservice();

        leaderboardEntryList = tempEntries;


        /*PetCareStateManager.instance.IncreaseXP(10000);*/
        

        // sort leaderboard entryies by current petXp(petXp)
        for (int i = 0; i < leaderboardEntryList.Count; i++)
        {
            for (int j = i + 1; j < leaderboardEntryList.Count; j++)
            {
                if (leaderboardEntryList[j].petXp > leaderboardEntryList[i].petXp)
                {
                    // Swap
                    LeaderboardEntry temp = leaderboardEntryList[i];
                    leaderboardEntryList[i] = leaderboardEntryList[j];
                    leaderboardEntryList[j] = temp;
                }
            }
        }

        // add container and leaderboard entries
        leaderboardEntryTransformList = new List<Transform>();
        foreach (LeaderboardEntry leaderboardEntry in leaderboardEntryList)
        {
            CreateLeaderboardEntryTransform(leaderboardEntry, entryContainer, leaderboardEntryTransformList);
        }

        Debug.Log($"Start()");
        /*Debug.Log($"");*/

    }



//  Methods  --------------------------------------

private async Task<List<LeaderboardEntry>> TestMicroservice()
    {
        var beamContext = BeamContext.Default;
        await beamContext.OnReady;

        Debug.Log($"beamContext.PlayerId = {beamContext.PlayerId}");

        _LeaderboardServiceClient = new LeaderboardServiceClient();

        // - Save leaderboard data example
        /*bool isSuccess = await _LeaderboardServiceClient.SaveEntry("bird", "flapper", 4, 6000);*/

        // - Result = true
        /*Debug.Log($"SaveEntry() isSuccess = {isSuccess}");*/

        // #3 - Call Microservice
        List<string> jsonEntry = await _LeaderboardServiceClient.GetAllEntries();
        List<LeaderboardEntry> entryList = new List<LeaderboardEntry>();

        // Convert JSON string to object
        foreach (string entry in jsonEntry)
        {
            // Parse json string to .net
            JObject parsedJson = JObject.Parse(entry);

            string playerName = (string)parsedJson["playerName"];
            string petName = (string)parsedJson["petName"];
            int petRank = (int)parsedJson["petRank"];
            int petXp = (int)parsedJson["petXp"];

            // populate current leaderboard list
            entryList.Add
            (
                new LeaderboardEntry { playerName = playerName, petName = petName, petRank = petRank, petXp = petXp, }
            );


        }

        return entryList;
       
    }

    // Round petXp to nearest whole number
    public int getPetXp()
    {
        float petXp = petDataRef.petData.xp;
        int x = (int)Math.Round(petXp);

        return x;
    }


    public int getPetRank()
    {
        int petRank = petDataRef.petData.rank;
        return petRank;
    }

    // method to create single leaderboard entry
    private void CreateLeaderboardEntryTransform(LeaderboardEntry leaderboardEntry, Transform container, List<Transform> transformList )
    {
        float templateHeight = 20f;
        Transform entryTransform = Instantiate(entryTemplate, container);
        RectTransform entryRectTransform = entryTransform.GetComponent<RectTransform>();
        entryRectTransform.anchoredPosition = new Vector2(0, -templateHeight * transformList.Count);
        entryTransform.gameObject.SetActive(true);

        // create number suffix for each entry
        int rank = transformList.Count + 1;
        string rankString;
        switch (rank)
        {
            default:
                rankString = rank + "TH"; break;

            case 1: rankString = "1ST"; break;
            case 2: rankString = "2ND"; break;
            case 3: rankString = "3RD"; break;
        }

        // replace ui text with leaderboard data
        entryTransform.Find("petStanding").GetComponent<Text>().text = rankString;

        string playerName = leaderboardEntry.playerName;
        entryTransform.Find("playerName").GetComponent<Text>().text = playerName.ToString();

        string petName = leaderboardEntry.petName;
        entryTransform.Find("petName").GetComponent<Text>().text = petName.ToString();

        int petRank = leaderboardEntry.petRank;
        entryTransform.Find("petRank").GetComponent<Text>().text = petRank.ToString();

        int petXp = leaderboardEntry.petXp;
        entryTransform.Find("petXp").GetComponent<Text>().text = petXp.ToString();

        transformList.Add(entryTransform);
    }

    // Obect that represents a single entry
    private class LeaderboardEntry
    {
        public string playerName;
        public string petName;
        public int petRank;
        public int petXp;
    }
   

}
