using System.Collections;
using System.Collections.Generic;
using Beamable.Common.Leaderboards;
using Beamable.Leaderboards;
using Beamable.Common;
using Beamable.Common.Api.Leaderboards;
using Beamable;
using UnityEngine;
using System;
using System.Threading.Tasks;
using Beamable.Common.Content;
using UnityEngine.SocialPlatforms.Impl;
using Beamable.Api.Autogenerated.Models;
using RankEntry = Beamable.Common.Api.Leaderboards.RankEntry;
using LeaderBoardView = Beamable.Common.Api.Leaderboards.LeaderBoardView;
using TMPro;
using UnityEngine.UI;
using Unity.Mathematics;
using Random = UnityEngine.Random;

public class LeaderboardServiceTest : MonoBehaviour
{
    //  Variables/Fields  ---------------------------------------
    [SerializeField]  private PetDataRef petDataRef;

    private Transform entryContainer;
    private Transform entryTemplate;


    //  Unity Methods  --------------------------------

    private void Awake()
    {
        entryContainer = transform.Find("leaderboardEntryContainer");
        entryTemplate = transform.Find("leaderboardEntry");

        entryTemplate.gameObject.SetActive(false);

        // Populate leaderboard with mock players
        float templateHeight = 30f;
        for(int i = 0; i < 10; i++)
        {
            Transform entryTransform = Instantiate(entryTemplate, entryContainer);
            RectTransform entryRectTransform = entryTransform.GetComponent<RectTransform>();
            entryRectTransform.anchoredPosition = new Vector2(0, -templateHeight * i);
            entryTransform.gameObject.SetActive(true);

            // create number suffix
            int rank = i + 1;
            string rankString;
            switch (rank)
            {
                default:
                    rankString = rank + "TH"; break;

                case 1: rankString = "1ST"; break;
                case 2: rankString = "2ND"; break;
                case 3: rankString = "3RD"; break;
            }

            entryTransform.Find("petRank").GetComponent<Text>().text = rankString;

            int petId = Random.Range(0, 5000);

            entryTransform.Find("petId").GetComponent<Text>().text = petId.ToString();

            string playerId = "tester";

            entryTransform.Find("playerId").GetComponent<Text>().text = playerId.ToString();

            int score = Random.Range(0, 10000);

            entryTransform.Find("score").GetComponent<Text>().text = score.ToString();

        }
    }


    private void Start()
    {
        Debug.Log($"Start()");

        Debug.Log(petDataRef.petData.petname);
    }


    public void Update()
    {
        
    }



    //  Methods  --------------------------------------

    // function to create leaderboard entry
    private void CreateHighscoreEntryTransform(HighscoreEntry highscoreEntry, Transform container, List<Transform> transformList )
    {

    }

    // represents a single entry
    private class HighscoreEntry
    {
        public int score;
        public string name;
    }
   

}
