using System.Collections;
using System.Collections.Generic;
using Beamable.Common.Leaderboards;
using Beamable.Leaderboards;
using Beamable.Common;
using Beamable.Common.Api.Leaderboards;
using Beamable;
using UnityEngine;
using System;
using System.Threading.Tasks;
using Beamable.Common.Content;
using UnityEngine.SocialPlatforms.Impl;
using Beamable.Api.Autogenerated.Models;
using RankEntry = Beamable.Common.Api.Leaderboards.RankEntry;
using LeaderBoardView = Beamable.Common.Api.Leaderboards.LeaderBoardView;
using TMPro;
using UnityEngine.UI;
using Unity.Mathematics;
using Random = UnityEngine.Random;
using PubNubMessaging.Core;

public class LeaderboardServiceTest : MonoBehaviour
{
    //  Variables/Fields  ---------------------------------------
    [SerializeField] public PetDataRef petDataRef;
    public PetLocalData petLocalRef;

    [SerializeField] public Transform entryContainer;
    [SerializeField] public Transform entryTemplate;
    private List<HighscoreEntry> highscoreEntryList;
    private List<Transform> highscoreEntryTransformList;

    


    //  Unity Methods  --------------------------------

    private void Awake()
    {
        entryTemplate.gameObject.SetActive(false);

        // Populate leaderboard with mock players and pet database values
        highscoreEntryList = new List<HighscoreEntry>()
        {
            new HighscoreEntry{ petId = getPetId(), playerId = 1000, petRank = getPetRank(), score = getPetXp()},
            new HighscoreEntry{ petId = "27", playerId = 1000, petRank = 5, score = Random.Range(0, 8000)},
            new HighscoreEntry{ petId = "3", playerId = 1000, petRank = 4, score = Random.Range(0, 5000)},
            new HighscoreEntry{ petId = "7", playerId = 1000, petRank = 9, score = Random.Range(0, 10000)},
            new HighscoreEntry{ petId = "87", playerId = 1000, petRank = 6, score = Random.Range(0, 13000)},
            new HighscoreEntry{ petId = "4", playerId = 1000, petRank = 1, score = Random.Range(0, 6000)},
            new HighscoreEntry{ petId = "10", playerId = 1000, petRank = 8, score = Random.Range(0, 3000)},
            new HighscoreEntry{ petId = "53", playerId = 1000, petRank = 7, score = Random.Range(0, 15000)},
            new HighscoreEntry{ petId = "2", playerId = 1000, petRank = 3, score = Random.Range(0, 7000)},
            new HighscoreEntry{ petId = "11", playerId = 1000, petRank = 10, score = Random.Range(0, 10000)}
        };

        // sort leaderboard entryies by current score(petXp)
        /*for (int i = 0; i < highscoreEntryList.Count; i++)
        {
            for (int j = i + 1; j < highscoreEntryList.Count; j++)
            {
                if (highscoreEntryList[j].score > highscoreEntryList[i].score)
                {
                    // Swap
                    HighscoreEntry temp = highscoreEntryList[i];
                    highscoreEntryList[i] = highscoreEntryList[j];
                    highscoreEntryList[j] = temp;
                }
            }
        }*/

        // add container and leaderboard entries
        highscoreEntryTransformList = new List<Transform>();
        foreach ( HighscoreEntry highscoreEntry in highscoreEntryList)
        {
            CreateHighscoreEntryTransform(highscoreEntry, entryContainer, highscoreEntryTransformList);
        }

        Debug.Log($"Start()");

        Debug.Log(petLocalRef.petID);
    }


    //  Methods  --------------------------------------

    // Round petXp to nearest whole number
    public int getPetXp()
    {
        float petXp = petDataRef.petData.xp;
        int x = (int)Math.Round(petXp);

        return x;
    }

    public string getPetId()
    {

        string petId = petLocalRef.petID;
        petId = "1";

        return petId;
    }

    public int getPetRank()
    {
        int petRank = petDataRef.petData.rank;
        return petRank;
    }

    // method to create single leaderboard entry
    private void CreateHighscoreEntryTransform(HighscoreEntry highscoreEntry, Transform container, List<Transform> transformList )
    {
        float templateHeight = 20f;
        Transform entryTransform = Instantiate(entryTemplate, container);
        RectTransform entryRectTransform = entryTransform.GetComponent<RectTransform>();
        entryRectTransform.anchoredPosition = new Vector2(0, -templateHeight * transformList.Count);
        entryTransform.gameObject.SetActive(true);

        // create number suffix
        int rank = transformList.Count + 1;
        string rankString;
        switch (rank)
        {
            default:
                rankString = rank + "TH"; break;

            case 1: rankString = "1ST"; break;
            case 2: rankString = "2ND"; break;
            case 3: rankString = "3RD"; break;
        }

        entryTransform.Find("petStanding").GetComponent<Text>().text = rankString;

        string petId = highscoreEntry.petId;

        entryTransform.Find("petId").GetComponent<Text>().text = petId.ToString();

        int playerId = highscoreEntry.playerId;

        entryTransform.Find("playerId").GetComponent<Text>().text = playerId.ToString();

        int petRank = highscoreEntry.petRank;

        entryTransform.Find("petRank").GetComponent<Text>().text = petRank.ToString();

        int score = highscoreEntry.score;

        entryTransform.Find("score").GetComponent<Text>().text = score.ToString();

        transformList.Add(entryTransform);
    }

    // represents a single entry
    private class HighscoreEntry
    {
        public string petId;
        public int playerId;
        public int petRank;
        public int score;
    }
   

}
