//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.Microservices.ExtraPlayerDataService"/> </summary
    public sealed class ExtraPlayerDataServiceClient : MicroserviceClient, Beamable.Common.IHaveServiceName
    {
        
        public ExtraPlayerDataServiceClient(BeamContext context = null) : 
                base(context)
        {
        }
        
        public string ServiceName
        {
            get
            {
                return "ExtraPlayerDataService";
            }
        }
        
        /// <summary>
        /// Call the ServerCall method on the ExtraPlayerDataService microservice
        /// <see cref="Beamable.Microservices.ExtraPlayerDataService.ServerCall"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Common.Unit> ServerCall()
        {
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            return this.Request<Beamable.Common.Unit>("ExtraPlayerDataService", "ServerCall", serializedFields);
        }
        
        /// <summary>
        /// Call the CreateEntry method on the ExtraPlayerDataService microservice
        /// <see cref="Beamable.Microservices.ExtraPlayerDataService.CreateEntry"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Common.Unit> CreateEntry(string _playerId, int _introTutorial, int _eatTutorial, int _showerTutorial, int _inventoryTutorial)
        {
            object raw__playerId = _playerId;
            object raw__introTutorial = _introTutorial;
            object raw__eatTutorial = _eatTutorial;
            object raw__showerTutorial = _showerTutorial;
            object raw__inventoryTutorial = _inventoryTutorial;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("_playerId", raw__playerId);
            serializedFields.Add("_introTutorial", raw__introTutorial);
            serializedFields.Add("_eatTutorial", raw__eatTutorial);
            serializedFields.Add("_showerTutorial", raw__showerTutorial);
            serializedFields.Add("_inventoryTutorial", raw__inventoryTutorial);
            return this.Request<Beamable.Common.Unit>("ExtraPlayerDataService", "CreateEntry", serializedFields);
        }
        
        /// <summary>
        /// Call the UpdateTutorial method on the ExtraPlayerDataService microservice
        /// <see cref="Beamable.Microservices.ExtraPlayerDataService.UpdateTutorial"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Common.Unit> UpdateTutorial(string _playerId, string _tutorialDone)
        {
            object raw__playerId = _playerId;
            object raw__tutorialDone = _tutorialDone;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("_playerId", raw__playerId);
            serializedFields.Add("_tutorialDone", raw__tutorialDone);
            return this.Request<Beamable.Common.Unit>("ExtraPlayerDataService", "UpdateTutorial", serializedFields);
        }
        
        /// <summary>
        /// Call the UpdateEntryByPlayerId method on the ExtraPlayerDataService microservice
        /// <see cref="Beamable.Microservices.ExtraPlayerDataService.UpdateEntryByPlayerId"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Common.Unit> UpdateEntryByPlayerId(string _playerId, int _introTutorial, int _eatTutorial, int _showerTutorial, int _inventoryTutorial)
        {
            object raw__playerId = _playerId;
            object raw__introTutorial = _introTutorial;
            object raw__eatTutorial = _eatTutorial;
            object raw__showerTutorial = _showerTutorial;
            object raw__inventoryTutorial = _inventoryTutorial;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("_playerId", raw__playerId);
            serializedFields.Add("_introTutorial", raw__introTutorial);
            serializedFields.Add("_eatTutorial", raw__eatTutorial);
            serializedFields.Add("_showerTutorial", raw__showerTutorial);
            serializedFields.Add("_inventoryTutorial", raw__inventoryTutorial);
            return this.Request<Beamable.Common.Unit>("ExtraPlayerDataService", "UpdateEntryByPlayerId", serializedFields);
        }
        
        /// <summary>
        /// Call the UpdateEntryTest method on the ExtraPlayerDataService microservice
        /// <see cref="Beamable.Microservices.ExtraPlayerDataService.UpdateEntryTest"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Common.Unit> UpdateEntryTest(string _id, string _playerId)
        {
            object raw__id = _id;
            object raw__playerId = _playerId;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("_id", raw__id);
            serializedFields.Add("_playerId", raw__playerId);
            return this.Request<Beamable.Common.Unit>("ExtraPlayerDataService", "UpdateEntryTest", serializedFields);
        }
        
        /// <summary>
        /// Call the GetEntryByPlayerId method on the ExtraPlayerDataService microservice
        /// <see cref="Beamable.Microservices.ExtraPlayerDataService.GetEntryByPlayerId"/>
        /// </summary>
        public Beamable.Common.Promise<string> GetEntryByPlayerId(string playerId)
        {
            object raw_playerId = playerId;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("playerId", raw_playerId);
            return this.Request<string>("ExtraPlayerDataService", "GetEntryByPlayerId", serializedFields);
        }
    }
    
    internal sealed class MicroserviceParametersExtraPlayerDataServiceClient
    {
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_String : MicroserviceClientDataWrapper<string>
        {
        }
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_Int32 : MicroserviceClientDataWrapper<int>
        {
        }
    }
    
    [BeamContextSystemAttribute()]
    public static class ExtensionsForExtraPlayerDataServiceClient
    {
        
        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute()]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            builder.AddScoped<ExtraPlayerDataServiceClient>();
        }
        
        public static ExtraPlayerDataServiceClient ExtraPlayerDataService(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<ExtraPlayerDataServiceClient>();
        }
    }
}
