//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.Microservices.GameServer"/> </summary
    public sealed class GameServerClient : MicroserviceClient, Beamable.Common.IHaveServiceName
    {
        
        public GameServerClient(BeamContext context = null) : 
                base(context)
        {
        }
        
        public string ServiceName
        {
            get
            {
                return "GameServer";
            }
        }
        
        /// <summary>
        /// Call the SaveEntry method on the GameServer microservice
        /// <see cref="Beamable.Microservices.GameServer.SaveEntry"/>
        /// </summary>
        public Beamable.Common.Promise<bool> SaveEntry(string playerName, string petName, int petRank, int petXp)
        {
            object raw_playerName = playerName;
            object raw_petName = petName;
            object raw_petRank = petRank;
            object raw_petXp = petXp;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("playerName", raw_playerName);
            serializedFields.Add("petName", raw_petName);
            serializedFields.Add("petRank", raw_petRank);
            serializedFields.Add("petXp", raw_petXp);
            return this.Request<bool>("GameServer", "SaveEntry", serializedFields);
        }
        
        /// <summary>
        /// Call the GetEntry method on the GameServer microservice
        /// <see cref="Beamable.Microservices.GameServer.GetEntry"/>
        /// </summary>
        public Beamable.Common.Promise<System.Collections.Generic.List<string>> GetEntry(string playerName, string petName, int petRank, int petXp)
        {
            object raw_playerName = playerName;
            object raw_petName = petName;
            object raw_petRank = petRank;
            object raw_petXp = petXp;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("playerName", raw_playerName);
            serializedFields.Add("petName", raw_petName);
            serializedFields.Add("petRank", raw_petRank);
            serializedFields.Add("petXp", raw_petXp);
            return this.Request<System.Collections.Generic.List<string>>("GameServer", "GetEntry", serializedFields);
        }
    }
    
    internal sealed class MicroserviceParametersGameServerClient
    {
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_String : MicroserviceClientDataWrapper<string>
        {
        }
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_Int32 : MicroserviceClientDataWrapper<int>
        {
        }
    }
    
    [BeamContextSystemAttribute()]
    public static class ExtensionsForGameServerClient
    {
        
        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute()]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            builder.AddScoped<GameServerClient>();
        }
        
        public static GameServerClient GameServer(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<GameServerClient>();
        }
    }
}
