//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.Microservices.LeaderboardService"/> </summary
    public sealed class LeaderboardServiceClient : MicroserviceClient, Beamable.Common.IHaveServiceName
    {
        
        public LeaderboardServiceClient(BeamContext context = null) : 
                base(context)
        {
        }
        
        public string ServiceName
        {
            get
            {
                return "LeaderboardService";
            }
        }
        
        /// <summary>
        /// Call the CreateEntry method on the LeaderboardService microservice
        /// <see cref="Beamable.Microservices.LeaderboardService.CreateEntry"/>
        /// </summary>
        public Beamable.Common.Promise<bool> CreateEntry(string _playerName, string _petName, int _petRank, int _petXp)
        {
            object raw__playerName = _playerName;
            object raw__petName = _petName;
            object raw__petRank = _petRank;
            object raw__petXp = _petXp;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("_playerName", raw__playerName);
            serializedFields.Add("_petName", raw__petName);
            serializedFields.Add("_petRank", raw__petRank);
            serializedFields.Add("_petXp", raw__petXp);
            return this.Request<bool>("LeaderboardService", "CreateEntry", serializedFields);
        }
        
        /// <summary>
        /// Call the UpdateRank method on the LeaderboardService microservice
        /// <see cref="Beamable.Microservices.LeaderboardService.UpdateRank"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Common.Unit> UpdateRank(string _playerName, int _petRank)
        {
            object raw__playerName = _playerName;
            object raw__petRank = _petRank;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("_playerName", raw__playerName);
            serializedFields.Add("_petRank", raw__petRank);
            return this.Request<Beamable.Common.Unit>("LeaderboardService", "UpdateRank", serializedFields);
        }
        
        /// <summary>
        /// Call the UpdateXp method on the LeaderboardService microservice
        /// <see cref="Beamable.Microservices.LeaderboardService.UpdateXp"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Common.Unit> UpdateXp(string _playerName, int _petXp)
        {
            object raw__playerName = _playerName;
            object raw__petXp = _petXp;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("_playerName", raw__playerName);
            serializedFields.Add("_petXp", raw__petXp);
            return this.Request<Beamable.Common.Unit>("LeaderboardService", "UpdateXp", serializedFields);
        }
        
        /// <summary>
        /// Call the GetAllEntries method on the LeaderboardService microservice
        /// <see cref="Beamable.Microservices.LeaderboardService.GetAllEntries"/>
        /// </summary>
        public Beamable.Common.Promise<System.Collections.Generic.List<string>> GetAllEntries()
        {
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            return this.Request<System.Collections.Generic.List<string>>("LeaderboardService", "GetAllEntries", serializedFields);
        }
    }
    
    internal sealed class MicroserviceParametersLeaderboardServiceClient
    {
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_String : MicroserviceClientDataWrapper<string>
        {
        }
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_Int32 : MicroserviceClientDataWrapper<int>
        {
        }
    }
    
    [BeamContextSystemAttribute()]
    public static class ExtensionsForLeaderboardServiceClient
    {
        
        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute()]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            builder.AddScoped<LeaderboardServiceClient>();
        }
        
        public static LeaderboardServiceClient LeaderboardService(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<LeaderboardServiceClient>();
        }
    }
}
