//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.Microservices.LeaderboardService"/> </summary
    public sealed class LeaderboardServiceClient : MicroserviceClient, Beamable.Common.IHaveServiceName
    {
        
        public LeaderboardServiceClient(BeamContext context = null) : 
                base(context)
        {
        }
        
        public string ServiceName
        {
            get
            {
                return "LeaderboardService";
            }
        }
        
        /// <summary>
        /// Call the ServerCall method on the LeaderboardService microservice
        /// <see cref="Beamable.Microservices.LeaderboardService.ServerCall"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Common.Unit> ServerCall()
        {
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            return this.Request<Beamable.Common.Unit>("LeaderboardService", "ServerCall", serializedFields);
        }
    }
    
    internal sealed class MicroserviceParametersLeaderboardServiceClient
    {
    }
    
    [BeamContextSystemAttribute()]
    public static class ExtensionsForLeaderboardServiceClient
    {
        
        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute()]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            builder.AddScoped<LeaderboardServiceClient>();
        }
        
        public static LeaderboardServiceClient LeaderboardService(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<LeaderboardServiceClient>();
        }
    }
}
