//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.Microservices.LeaderboardService"/> </summary
    public sealed class LeaderboardServiceClient : MicroserviceClient, Beamable.Common.IHaveServiceName
    {
        
        public LeaderboardServiceClient(BeamContext context = null) : 
                base(context)
        {
        }
        
        public string ServiceName
        {
            get
            {
                return "LeaderboardService";
            }
        }
        
        /// <summary>
        /// Call the SaveEntry method on the LeaderboardService microservice
        /// <see cref="Beamable.Microservices.LeaderboardService.SaveEntry"/>
        /// </summary>
        public Beamable.Common.Promise<bool> SaveEntry(string _playerName, string _petName, int _petRank, int _petXp)
        {
            object raw__playerName = _playerName;
            object raw__petName = _petName;
            object raw__petRank = _petRank;
            object raw__petXp = _petXp;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("_playerName", raw__playerName);
            serializedFields.Add("_petName", raw__petName);
            serializedFields.Add("_petRank", raw__petRank);
            serializedFields.Add("_petXp", raw__petXp);
            return this.Request<bool>("LeaderboardService", "SaveEntry", serializedFields);
        }
        
        /// <summary>
        /// Call the UpdateEntry method on the LeaderboardService microservice
        /// <see cref="Beamable.Microservices.LeaderboardService.UpdateEntry"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Common.Unit> UpdateEntry(string _playerName)
        {
            object raw__playerName = _playerName;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("_playerName", raw__playerName);
            return this.Request<Beamable.Common.Unit>("LeaderboardService", "UpdateEntry", serializedFields);
        }
        
        /// <summary>
        /// Call the GetEntry method on the LeaderboardService microservice
        /// <see cref="Beamable.Microservices.LeaderboardService.GetEntry"/>
        /// </summary>
        public Beamable.Common.Promise<System.Collections.Generic.List<string>> GetEntry(string _playerName)
        {
            object raw__playerName = _playerName;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("_playerName", raw__playerName);
            return this.Request<System.Collections.Generic.List<string>>("LeaderboardService", "GetEntry", serializedFields);
        }
    }
    
    internal sealed class MicroserviceParametersLeaderboardServiceClient
    {
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_String : MicroserviceClientDataWrapper<string>
        {
        }
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_Int32 : MicroserviceClientDataWrapper<int>
        {
        }
    }
    
    [BeamContextSystemAttribute()]
    public static class ExtensionsForLeaderboardServiceClient
    {
        
        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute()]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            builder.AddScoped<LeaderboardServiceClient>();
        }
        
        public static LeaderboardServiceClient LeaderboardService(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<LeaderboardServiceClient>();
        }
    }
}
