//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.Microservices.walletService"/> </summary
    public sealed class walletServiceClient : MicroserviceClient, Beamable.Common.IHaveServiceName
    {
        
        public walletServiceClient(BeamContext context = null) : 
                base(context)
        {
        }
        
        public string ServiceName
        {
            get
            {
                return "walletService";
            }
        }
        
        /// <summary>
        /// Call the ServerCall method on the walletService microservice
        /// <see cref="Beamable.Microservices.walletService.ServerCall"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Common.Unit> ServerCall()
        {
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            return this.Request<Beamable.Common.Unit>("walletService", "ServerCall", serializedFields);
        }
    }
    
    internal sealed class MicroserviceParameterswalletServiceClient
    {
    }
    
    [BeamContextSystemAttribute()]
    public static class ExtensionsForwalletServiceClient
    {
        
        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute()]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            builder.AddScoped<walletServiceClient>();
        }
        
        public static walletServiceClient walletService(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<walletServiceClient>();
        }
    }
}
