using Beamable;
using Beamable.Api.Autogenerated.Models;
using Beamable.Common.Inventory;
using Beamable.InventoryService;
using System.Collections;
using System.Collections.Generic;
using TMPro;
using UnityEngine;
public class UpdateContentOnEvent : MonoBehaviour
{
    [Header("Currency Reference")]
    public CurrencyRef _currencyRefPrimary; // Add this reference in the Inspector
    [Space]
    public Canvas coinCanvas;
    [Space]
    public TextMeshProUGUI coinText;

    private BeamContext _beamContext;

    private long targetAmount;
    private long currentAmount = 0;

    readonly WaitForSeconds _waitForSeconds = new WaitForSeconds(0.02f);


    //private void Start()
    //{
    //    Debug.Log("Getting Coins");
    //    GetCurruncyValue();
    //}

    private void OnEnable()
    {

    }

    private void OnDisable()
    {

    }

    public async void GetCurruncyValue()
    {
        Debug.Log("GetCurruncyValue");
        var ctx = await BeamContext.Default.Instance;

        //var ctx = BeamContext.InParent(this);
        await ctx.OnReady;


        // Get the current balance of the user's primary currency
        var currencyContentPrimary = await _currencyRefPrimary.Resolve();
        var currencyBalances = await ctx.Api.InventoryService.GetCurrent();

        if (currencyBalances.currencies.TryGetValue(currencyContentPrimary.Id, out var userCurrencyBalance))
        {
            Debug.Log(userCurrencyBalance);
            coinCanvas.enabled = true;
            targetAmount = userCurrencyBalance;
            ctx.CoroutineService.StartCoroutine(DisplayCurrency());
        }


    }

    private IEnumerator DisplayCurrency()
    {
        long deltaTotal = targetAmount - currentAmount;
        long deltaStep = deltaTotal / 50;

        if (deltaStep == 0)
        {
            deltaStep = deltaTotal < 0 ? -1 : 1;
        }

        while (currentAmount != targetAmount)

        {
            currentAmount += deltaStep;

            if (deltaTotal > 0 && currentAmount > targetAmount)
            {
                currentAmount = targetAmount;
            }

            else if (deltaTotal < 0 && currentAmount < targetAmount)
            {
                currentAmount = targetAmount;
            }

            coinText.text = currentAmount.ToString();
            yield return _waitForSeconds;
        }
    }
}
