using Beamable.Api.Autogenerated.Models;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEditor.PackageManager;
using UnityEngine;
using UnityEngine.AI;
using UnityEngine.InputSystem.HID;

public class NavMeshController : MonoBehaviour
{

    public GameObject Target;

    #region PRIVATE
    private NavMeshAgent Agent;
    RaycastHit HitInfo = new RaycastHit();

    private Vector2 smoothDeltaPosition = Vector2.zero;
    private Vector2 velocity = Vector2.zero;

    #endregion
    // Start is called before the first frame update
    void Start()
    {
        Agent = GetComponent<NavMeshAgent>();
       
    }

    void Update()
    {
        Agent.destination = Target.transform.position;
        if (Input.GetMouseButtonDown(0))
        {
            Ray ray = Camera.main.ScreenPointToRay(Input.mousePosition);
            if (Physics.Raycast(ray.origin, ray.direction, out HitInfo))
            {
                Debug.Log("Hit Info  " + HitInfo.point);
                Target.transform.position = HitInfo.point;
                Agent.SetDe stination(Target.transform.position);
            }
        }
    }

    void _Move()
    {

    }
}
