using System.Collections;
using System.Collections.Generic;
using Beamable.Common.Leaderboards;
using Beamable.Leaderboards;
using Beamable.Common;
using Beamable.Common.Api.Leaderboards;
using Beamable;
using UnityEngine;
using System;
using System.Threading.Tasks;
using Beamable.Common.Content;
using UnityEngine.SocialPlatforms.Impl;
using Beamable.Api.Autogenerated.Models;
using RankEntry = Beamable.Common.Api.Leaderboards.RankEntry;
using LeaderBoardView = Beamable.Common.Api.Leaderboards.LeaderBoardView;
using TMPro;

public class LeaderboardServiceTest : MonoBehaviour
{
    //  Fields  ---------------------------------------
    [SerializeField] private LeaderboardRef _leaderboardRef = null;
    [SerializeField] private double _score = 100;
    [SerializeField] public TextMeshProUGUI TxtAlias;
    /*[SerializeField] public TextMeshProUGUI TxtScore;*/
    private RankEntry _rankEntry;

    //  Unity Methods  --------------------------------

    protected void Start()
    {
        Debug.Log($"Start()");

        LeaderboardServiceSetScore(_leaderboardRef.Id, _score);
    }

    public void Update()
    {
        // Render value
        /*TxtScore.text = $"{_score:00000}";*/
        /*TxtAlias.text = $"{_leaderboardRef.Id:ALIAS}";*/
    }



    //  Methods  --------------------------------------
    private async void LeaderboardServiceSetScore(string id, double score)
    {
        var beamContext = BeamContext.Default;
        await beamContext.OnReady;

        Debug.Log($"beamContext.PlayerId = {beamContext.PlayerId}");


        await beamContext.Api.LeaderboardService.SetScore(id, score);

        Debug.Log($"LeaderboardService.SetScore({id},{score})");
    }

}
