using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Fusion;
using Unity.VisualScripting;
using UnityEngine.AI;
using TMPro;
using System.Xml.Linq;
using static UnityEngine.RuleTile.TilingRuleOutput;
using Beamable.Api.Autogenerated.Models;
using DG.Tweening;
public class NavmeshMultiplayer : NetworkBehaviour, IBeforeUpdate
{
    #region PUBLIC VARIABLES
    [Header("SCRIPTABLE OBJECTS")]
    public InputValue m_input_value;
    public PetConfigs PetConfigs;
    [Space]
    public TextMeshPro nameText;
    [Header("Navmesh Agent")]
    public NavMeshAgent m_agent;
    [Header("ANIMATOR")]
    public PetAnimation GenratedPet;

    [Header("Script Refrence")]
    private PathPointManager path_point;

    public NetworkString<_32> playerName;
    public PlayerRef playerRef;
    public List<Vector3> move_positions;
    [Space]
    public _PlayerConfigs playerconfigs;
    [Space]
    public float MySpeed;
    public float MyStamina;
    #endregion

    #region Private variables
    private Vector3 m_currunt_pos;
    private float m_distance;
    private int m_currunt_index;
    public bool IsServer;
    public bool IsLocalPlayer;
    public bool RaceComplete;
    [Space]
    public float NetworkedSetTap;
    public float MyNetworkSpeed;

    private NavMeshHit hit;
    private Vector3 finalPosition;
    private Vector3 WinPosition = Vector3.zero;
    #endregion

    #region NETWORKED OBJECTS
    [Networked] public string MyName { get; set; }
    [Networked] public int MyPathNumber { get; set; }
    [Networked] public string MyPrefabID { get; set; }

    [Networked, OnChangedRender(nameof(_OnWInNumberAlocated))]
    public int MyWiningNumber { get; set; }


    private NetworkTransform networkTransform;

    #endregion

    #region NETWORK FUCTIONS
    public override void Spawned() // fusionun startı
    {
        path_point = FindObjectOfType<PathPointManager>();
        SetLocalObjects();
        _SetupConfigs();
        networkTransform = GetComponent<NetworkTransform>();
        if (Runner.IsServer)
        {
            IsServer = true;
        }
        else
        {
            m_agent.enabled = false;
        }
        StartCoroutine(_GenrateMyPrefab());
    }

    IEnumerator _GenrateMyPrefab()
    {
        yield return new WaitForSecondsRealtime(1f);
        //Debug.Log("This Choroutine Worked " + gameObject.name);
        _GenratePetPrefab();
    }

    /// <summary>
    /// Remove random on Actual Project
    /// </summary>
    void _SetupConfigs()
    {
        m_agent.speed = Random.Range(3, PetConfigs.BaseSpeed);
        m_agent.acceleration = Random.Range(15, PetConfigs.Acceleration);
    }

    private void SetLocalObjects()
    {
        if (Utils.IsLocalPlayer(Object))
        {
            IsLocalPlayer = true;
            playerName = RaceManager.instance.LocalPlayerNickname;
            Debug.Log("Sending RPC with Name   " + playerName);
            MyName = playerName.ToString();
            RPC_SetNameAndPrefab(playerName, RaceManager.instance.PrefabID);

            _SetMyConfigs();

            //RPC FOR SENDING CONFIGS
            string s = JsonUtility.ToJson(RaceManager.instance._GetMyCOnfigs());
            Debug.Log(s + "    " + MyName);
            RPC_GetMyConfigs(s);

            nameText.text = playerName.ToString();
            gameObject.name = MyName.ToString();
            _SetupCamera();
        }
        else
        {
            //Debug.Log("My Name Is " + MyName);
            gameObject.name = MyName.ToString();
            nameText.text = MyName.ToString();
        }
    }

    #endregion

    #region UNITY METHODS

    private void OnEnable()
    {
        NetworkEventManager.e_get_set_go += _StartRun;
    }

    private void OnDisable()
    {
        NetworkEventManager.e_get_set_go -= _StartRun;
    }
    #endregion

    #region SETUP CONFIGS
    private void _SetMyConfigs()
    {
        PetConfigs.m_run_multiplier = playerconfigs.running;
        PetConfigs.m_swim_multiplier = playerconfigs.swimming;
        PetConfigs.m_climb_multiplier = playerconfigs.climbing;
        PetConfigs.m_fly_multiplier = playerconfigs.flying;
        PetConfigs.MyXp = (int)playerconfigs.xp;
        PetConfigs.MyCoins = playerconfigs.mycoins;
        PetConfigs.maxstemina = playerconfigs.maxStamina;

        RaceManager.instance.MyXP = PetConfigs.MyXp;
        RaceManager.instance.MyCoins = PetConfigs.MyCoins;

        MySpeed = PetConfigs.BaseSpeed + _GetMyStateMultiplier(playerconfigs.running);

        NetworkEventManager._EventConfigUpdated();
    }

    float _GetMyStateMultiplier(float _value)
    {
        return (1 + (_value / 100f));
        //return 10f;
    }

    #endregion

    #region COLISION DETECTION

    private void OnTriggerEnter(Collider other)
    {

        Debug.Log(other.tag);

        if (Runner.IsServer)
        {
            switch (other.tag)
            {
                case _Tags.WinLine:
                    Debug.Log("WINLINE COLIDED" + other.tag + "    " + MyName);
                    GetComponent<NavMeshAgent>().enabled = false;
                    GetComponent<Collider>().enabled = false;
                    Rigidbody rb = GetComponent<Rigidbody>();
                    rb.isKinematic = true;
                    MyWiningNumber = RaceManager.instance._GetMyWinningNo();
                    RaceComplete = true;
                    StartCoroutine(SetMyWinPosition());
                    nameText.GetComponent<LookAtCamera>().m_cam = NetworkCamera.Instance.WinCam.transform;
                    break;
                case _Tags.Water:
                    _ChangeAnimationHere(_AnimState.Swimming);
                    MySpeed = PetConfigs.BaseSpeed + _GetMyStateMultiplier(playerconfigs.swimming);
                    break;
                case _Tags.Flying:
                    _ChangeAnimationHere(_AnimState.Flying);
                    MySpeed = PetConfigs.BaseSpeed + _GetMyStateMultiplier(playerconfigs.flying);
                    break;
                case _Tags.Land:
                    _ChangeAnimationHere(_AnimState.Run);
                    MySpeed = PetConfigs.BaseSpeed + _GetMyStateMultiplier(playerconfigs.running);
                    break;
                case _Tags.Climbing:
                    _ChangeAnimationHere(_AnimState.Climbing);
                    MySpeed = PetConfigs.BaseSpeed + _GetMyStateMultiplier(playerconfigs.climbing);
                    break;

            }
        }
        else
        {
            switch (other.tag)
            {
                case _Tags.Water:
                    _ChangeAnimationHere(_AnimState.Swimming);
                    break;
                case _Tags.Flying:
                    _ChangeAnimationHere(_AnimState.Flying);
                    break;
                case _Tags.Land:
                    _ChangeAnimationHere(_AnimState.Run);
                    break;
                case _Tags.Climbing:
                    _ChangeAnimationHere(_AnimState.Climbing);
                    break;
            }
        }
    }
    #endregion

    #region WIN LOGC 
    private IEnumerator SetMyWinPosition()
    {
        Debug.Log("SetMyWinPosition " + MyName);

        yield return new WaitForSecondsRealtime(0.2f);
        int temp = MyWiningNumber - 1;
        Vector3 pos = RaceManager.instance.WinPoints[temp].position;
        //Quaternion Q = RaceManager.instance.WinPoints[temp].rotation;
        WinPosition = pos;
        //networkTransform.Teleport(pos, Q);
        yield return new WaitForEndOfFrame();
        Debug.Log("Position Set now Just Play win animation over here " + gameObject.name);
        _ChangeAnimationHere(_AnimState.Jump);
    }

    private void _OnWInNumberAlocated()
    {
        if (Utils.IsLocalPlayer(Object))
        {
            nameText.GetComponent<LookAtCamera>().m_cam = NetworkCamera.Instance.WinCam.transform;
            Debug.Log("Yes Win number is allowcated  " + MyWiningNumber + "      " + MyName);
            NetworkEventManager._EventWon(MyWiningNumber);
            NetwrokUI.Instance.WinUI.SetActive(true);
            NetworkCamera.Instance._ActiveWinScene();
            _ChangeAnimationHere(_AnimState.Jump);
            RaceManager.instance.MyWinNumber = MyWiningNumber;
        }
        else
        {
            nameText.GetComponent<LookAtCamera>().m_cam = NetworkCamera.Instance.WinCam.transform;
            Debug.Log("Chaning animation for all other " + MyName);
            _ChangeAnimationHere(_AnimState.Jump);
        }
        RaceManager.instance._CheckAllPlayerCompleted();

    }
    #endregion

    #region ANIMATION CAMERA
    private void _ChangeAnimationHere(_AnimState _state)
    {
        GenratedPet._ChangeAnimationState(_state);
    }

    void _SetupCamera()
    {
        NetworkCamera.Instance._SetUpCamera(transform);
    }
    #endregion

    #region RUN SETUP
    public void _SetUpMyInitialData(int pr)
    {
        MyPathNumber = pr;
    }

    public void _StartRun()
    {
        if (IsServer)
        {
            Debug.Log(MyPathNumber);
            _InitilizePath();
            m_currunt_pos = _GetNextPos(move_positions[m_currunt_index]);
            _SetDestination();
        }
        else
        {
            m_agent.enabled = false;
        }

        _ChangeAnimationHere(_AnimState.Run);
    }

    public void _SetPathBasedOnIndex()
    {
        MyPathNumber = playerRef.PlayerId;
    }

    #endregion

    #region FIXED UPDATED
    /// <summary>
    /// NETWORKED CALLS
    /// </summary>
    public override void FixedUpdateNetwork()
    {
        if (!m_input_value.m_enable_navmesh)
        {
            return;
        }


        if (Runner.TryGetInputForPlayer<NetworkInputData>(Object.InputAuthority, out var input)) // // this out keyword will find PlayerData script and assign the value all the information from that script and put it into input variable.
        {
            NetworkedSetTap = input.TapMultiplier;
            MyNetworkSpeed = input.Speed;
            WinPosition = input.direction;

            if (RaceComplete)
            {
                transform.position = input.direction;
            }

        }

        if (!IsServer || RaceComplete)
        {
            return;
        }

        //Debug.Log("Calculating");
        //CALCULATING FOR SPEED FROM TAPING

        m_agent.speed = MyNetworkSpeed * NetworkedSetTap;

        //FIND DISTNACE HERE
        _CalculateDistance();
        if (m_distance < 4f)
        {
            _ChangeCurruntPoint();
        }
    }

    #endregion

    #region GETPLAYER INPUT
    public NetworkInputData GetPlayerNetworkInput() // playerdataları işlediğimiz yer. Buraya değerleri gönderiyuz FUN da alıyoruz.
    {
        NetworkInputData data = new NetworkInputData();
        data.TapMultiplier = PetConfigs.TapMultiplier;
        data.Speed = MySpeed;
        data.direction = WinPosition;
        return data; // then we will return the data.
    }
    #endregion

    #region NAVMESH METHODS
    private void _ChangeCurruntPoint()
    {
        m_currunt_index++;
        if (m_currunt_index >= move_positions.Count)
        {
            //Debug.Log("Path Complete");
            return;
        }

        //Calculate all path here
        m_currunt_pos = _GetNextPos(move_positions[m_currunt_index]);
        _SetDestination();
    }
    /// <summary>
    /// Initilize path
    /// </summary>
    void _InitilizePath()
    {
        Debug.Log("My Path No  " + MyPathNumber + "   " + gameObject.name);
        move_positions = new List<Vector3>();
        move_positions = path_point.prePositions[MyPathNumber].m_positions;
    }

    public void _SetDestination()
    {
        NavMeshPath path = new NavMeshPath();
        NavMesh.CalculatePath(m_agent.transform.position, m_currunt_pos, NavMesh.AllAreas, path);
        m_agent.SetPath(path);
    }

    void _CalculateDistance()
    {
        m_distance = Vector3.Distance(m_currunt_pos, transform.position);
    }

    public Vector3 _GetNextPos(Vector3 _pos)
    {
        hit = new NavMeshHit();
        finalPosition = Vector3.zero;
        if (NavMesh.SamplePosition(_pos, out hit, 10, 1))
        {
            finalPosition = hit.position;
        }
        else
        {
            finalPosition = _pos;
        }
        return finalPosition;
    }

    #endregion

    #region RPC CLLAS AND RECIVERS
    [Rpc(sources: RpcSources.InputAuthority, RpcTargets.StateAuthority)]
    private void RPC_SetNameAndPrefab(NetworkString<_32> nickname, string _prefabid)
    {
        playerName = nickname;
        MyPrefabID = _prefabid;
        Debug.Log("My Prefab id is  " + _prefabid);
        _OnRecivedRPC();
    }

    [Rpc(sources: RpcSources.InputAuthority, RpcTargets.All)]
    private void RPC_GetMyConfigs(string _json)
    {
        Debug.Log("I am sending RPC");
        _OnReciveConfigs(_json);
    }

    private void _OnReciveConfigs(string _j)
    {
        Debug.Log("I recived RPC  " + gameObject.name + "   " + _j);
        playerconfigs = JsonUtility.FromJson<_PlayerConfigs>(_j);
        _SetMyConfigs();
    }

    void _OnRecivedRPC()
    {
        Debug.Log("Recived RPC HERE  " + Runner.IsServer + "  MY ACTUAL NAME IS   " + MyName);
        MyName = playerName.ToString();
        nameText.text = MyName.ToString();
        gameObject.name = MyName;
        _GenratePetPrefab();
    }

    private void _GenratePetPrefab()
    {
        //Debug.Log("This works on Server  only  " + Runner.IsServer);
        if (GenratedPet == null)
        {
            //Debug.Log("   MyName  " + MyName + "  MyPrefabID  " + MyPrefabID);
            GameObject obj = Instantiate(RaceManager.instance.PetPrefabHolder._GetMyPrefab(MyPrefabID), transform);
            GenratedPet = obj.GetComponent<PetAnimation>();
            gameObject.GetComponent<NetworkMecanimAnimator>().Animator = GenratedPet.Animator;
            //gameObject.GetComponent<NetworkMecanimAnimator>().enabled = true;
            obj.transform.localPosition = Vector3.zero;
            obj.transform.localRotation = Quaternion.identity;
            nameText.text = MyName.ToString();
            gameObject.name = MyName;

            //ADD PLAYER
            _GenratedPlayers G = new _GenratedPlayers();
            G.player = this;
            RaceManager.instance.TotalPlayers.Add(G);
            RaceManager.instance.TotalNumberOfPlayers++;

        }
        else
        {
            Debug.Log("ALready Genrated");
        }
    }

    public void BeforeUpdate()
    {
        //if (Utils.IsLocalPlayer(Object))
        //{
        //    //PetConfigs.TapMultiplier
        //}
    }

    #endregion
}

[System.Serializable]
public class _PlayerConfigs
{
    //Athletics Stats
    public int running, climbing, flying, swimming, intelligence, luck, rank, maxStamina, mycoins;
    public float xp;
}
