using System;
using System.Collections.Generic;
using System.Linq;
using Beamable.Api.Autogenerated.Models;
using Beamable.Common;
using Beamable.Server;
using MongoDB.Driver;
using UnityEngine;

namespace Beamable.Microservices
{
	[Microservice("LeaderboardService")]
	public class LeaderboardService : Microservice
	{
       
        [ClientCallable]
        public async Promise<bool> SaveEntry(string _playerName, string _petName, int _petRank, int _petXp)
        {
            bool isSuccess = false;

            try
            {
                // MongoDB connection
                var db = await Storage.GetDatabase<LeaderboardStorage>();
                var collection = db.GetCollection<PlayerEntry>("LeaderboardStorage");

                // filter for _playerName
                var filter = Builders<PlayerEntry>.Filter.Eq("playerName", _playerName);
                if (filter == null)
                {
                    Debug.Log($"{_playerName} does not exist");
                }

                // Return the leaderboard connected to _playerName
                var col = collection.Find(filter).ToList();
                col.ForEach(x =>
                {
                    if (x.playerName == _playerName)
                    {
                        Debug.Log($"{_playerName} already exists");

                        // to-do: if player exists, update their data
                    }
                    else
                    {
                        // create new data
                        collection.InsertOne(new PlayerEntry()
                        {
                            playerName = _playerName,
                            petName = _petName,
                            petRank = _petRank,
                            petXp = _petXp

                        });
                        Debug.Log($"{_playerName} added to database");
                    }
                });

                // add method to update data!!!

                isSuccess = true;
            }
            catch (Exception e)
            {

                Debug.LogError(e.Message);
            }

            return isSuccess;

        }

        [ClientCallable]
        public async void UpdateEntry(string _playerName)
        {
            // MongoDB connection
            var db = await Storage.GetDatabase<LeaderboardStorage>();
            var collection = db.GetCollection<PlayerEntry>("LeaderboardStorage");
            var filter = Builders<PlayerEntry>.Filter.Eq("playerName", _playerName);
        }

        [ClientCallable]
        public async Promise<List<string>> GetEntry(string _playerName)
        {
            // Filter entries based on playerName
            var filter = Builders<PlayerEntry>.Filter.Eq("playerName", _playerName);
            var db = await Storage.GetDatabase<LeaderboardStorage>();
            var collection = db.GetCollection<PlayerEntry>("LeaderboardStorage");
            var LeaderboardEntries = collection
               .Find(filter)
               .ToList();

            return LeaderboardEntries.Select(entry => entry.playerName + entry.petName + entry.petRank + entry.petXp).ToList();
        }


    }

    
}
