using System;
using System.Collections.Generic;
using System.Linq;
using Beamable.Api.Autogenerated.Models;
using Beamable.Common;
using Beamable.Server;
using MongoDB.Driver;
using UnityEngine;

namespace Beamable.Microservices
{
	[Microservice("LeaderboardService")]
	public class LeaderboardService : Microservice
	{
       
        [ClientCallable]
        public async Promise<bool> SaveEntry(string _playerName, string _petName, int _petRank, int _petXp)
        {
            bool isSuccess = false;

            try
            {
                // MongoDB connection
                var db = await Storage.GetDatabase<LeaderboardStorage>();
                var collection = db.GetCollection<PlayerEntry>("LeaderboardStorage");

                var filter = Builders<PlayerEntry>.Filter.Empty;
                if (filter != null)
                {
                    Debug.Log($"Test: Database already populated");
                }

                // create new data
                collection.InsertOne(new PlayerEntry()
                {
                    playerName = _playerName,
                    petName = _petName,
                    petRank = _petRank,
                    petXp = _petXp

                });
                Debug.Log($"{_playerName}'s data added to database");

                // add method to update data!!!

                isSuccess = true;
            }
            catch (Exception e)
            {

                Debug.LogError(e.Message);
            }

            return isSuccess;

        }

        [ClientCallable]
        public async void UpdateEntry(string _playerName)
        {
            // MongoDB connection
            var db = await Storage.GetDatabase<LeaderboardStorage>();
            var collection = db.GetCollection<PlayerEntry>("LeaderboardStorage");
            var filter = Builders<PlayerEntry>.Filter.Eq("playerName", _playerName);
        }

        [ClientCallable]
        public async Promise<List<String>> GetEntry(string _playerName)
        {
            // Filter entries based on playerName
            /*var filter = Builders<PlayerEntry>.Filter.Eq("playerName", _playerName);*/
            var db = await Storage.GetDatabase<LeaderboardStorage>();
            var collection = db.GetCollection<PlayerEntry>("LeaderboardStorage");
            var LeaderboardEntries = collection
               .Find(x => x.playerName == _playerName)
               .ToList();

            // Sort retrieved data into an object, then return list of said objects

            return LeaderboardEntries.Select(entry => entry.playerName + entry.petName + entry.petRank + entry.petXp).ToList();
        }


    }

    
}
