using System;
using System.Text.RegularExpressions;
using UnityEngine;
using UnityEngine.Events;
using Beamable.Api.Inventory;
using Beamable.Common.Api.Inventory;
using Beamable.Common.Inventory;
using TMPro;
using Beamable.Api.Autogenerated.Models;

namespace Beamable.InventoryService
{
    [Serializable]
    public class RefreshedUnityEvent : UnityEvent { }

    public class BeamableInventoryManager : MonoBehaviour
    {
        public static BeamableInventoryManager instance;
        // Events
        [HideInInspector] public RefreshedUnityEvent OnRefreshed = new RefreshedUnityEvent();

        // Fields
        private BeamContext _beamContext;
        private Api.Inventory.InventoryService _inventoryService;

        [Header("Currency Reference")]
        public CurrencyRef _currencyRefPrimary; // Add this reference in the Inspector

        [Header("UI elements for store stuff")]
        public TMP_Text itemNameText; // Reference to the ItemName TMP Text
        public TMP_InputField buyQuantityInput;
        public TMP_Text costOfItems;
        public GameObject notEnoughMoneyPopup;
        public GameObject confirmPurchasePopup;
        public GameObject itemNotRefreshedPopup;
        public GameObject tooManyBoughtPopup;
        [Space]
        [Header("Game Events")]
        public SimpleGameEvent OnrefreshContent;

        [Header("StoreScript")]
        public BuyQuantityManager buyQuantityManager;

        // Unity Methods
        private void Awake()
        {
            if (instance == null)
            {
                instance = this;
            }
            else
            {
                DestroyImmediate(instance);
            }
        }

        protected void Start()
        {
            SetupBeamable();
        }

        // Methods
        private async void SetupBeamable()
        {
            _beamContext = BeamContext.Default;
            await _beamContext.OnReady;

            _inventoryService = _beamContext.Api.InventoryService;
            // Add any initialization or setup code here
        }


        public async void AddCurrency(int amount)
        {
            if (_currencyRefPrimary == null)
            {
                Debug.LogError("_currencyRefPrimary is not assigned.");
                return;
            }

            while (_inventoryService == null)
            {
                await Utils._Waiter(50);
            }


            var currencyContentPrimary = await _currencyRefPrimary.Resolve();
            InventoryUpdateBuilder inventoryUpdateBuilder = new InventoryUpdateBuilder();
            inventoryUpdateBuilder.CurrencyChange(currencyContentPrimary.Id, +amount);

            await _inventoryService.Update(inventoryUpdateBuilder).Then(obj =>
            {
                if (OnRefreshed != null)
                {
                    Debug.Log($"AddCurrency() success.");
                    OnRefreshed.Invoke();

                }
                OnrefreshContent.Raise();
            });
        }

        public async void GetCurruncyValue()
        {
            if (_currencyRefPrimary == null)
            {
                Debug.LogError("_currencyRefPrimary is not assigned.");
                return;
            }
            // Acquire a context
            var ctx = await BeamContext.Default.Instance;

            // Get the current balance of the user's primary currency
            var currencyContentPrimary = await _currencyRefPrimary.Resolve();
            var currencyBalances = await ctx.Api.InventoryService.GetCurrent();

            if (currencyBalances.currencies.TryGetValue(currencyContentPrimary.Id, out var userCurrencyBalance))
            {
                Debug.Log(userCurrencyBalance);
            }
        }


        public async void PurchaseItems()
        {
            string itemName = Regex.Replace(itemNameText.text, @"\s+([A-Z])", "$1");
            int quantity = int.Parse(buyQuantityInput.text);
            int cost = int.Parse(costOfItems.text);

            // Acquire a context
            var ctx = await BeamContext.Default.Instance;

            // Get the current balance of the user's primary currency
            var currencyContentPrimary = await _currencyRefPrimary.Resolve();
            var currencyBalances = await ctx.Api.InventoryService.GetCurrent();

            // Check if the user has enough currency
            if (currencyBalances.currencies.TryGetValue(currencyContentPrimary.Id, out var userCurrencyBalance))
            {
                if (userCurrencyBalance >= cost)
                {
                    if (itemName == "CosmicBerryElectrolyteDrink" && quantity > 1 || itemName == "MiracleCognitiveSupplements" && quantity > 1 || itemName == "ProteinShake" && quantity > 1)
                    {
                        tooManyBoughtPopup.SetActive(true);
                        return;
                    }

                    if (await buyQuantityManager.IsItemPurchasable(itemName, quantity) == false)
                    {
                        itemNotRefreshedPopup.SetActive(true);
                        return;
                    }

                    confirmPurchasePopup.SetActive(false);

                    // Loop through the specified quantity
                    for (int i = 0; i < quantity; i++)
                    {
                        // Add the item to the user's inventory using Beamable API
                        await ctx.Inventory.Update(builder => builder.AddItem("items." + itemName));
                    }

                    // Deduct the cost from the user's currency
                    AddCurrency(-cost);

                    Debug.Log($"Successfully added {quantity} of {itemName} to the user's Beamable inventory. Removed {cost}$");
                }
                else
                {
                    notEnoughMoneyPopup.SetActive(true);
                }
            }
            else
            {
                Debug.LogError("Failed to retrieve user currency balance.");
            }
        }

        public void Refresh()
        {
            // Placeholder for refresh logic if needed
            Debug.Log("Inventory data refreshed.");
            OnRefreshed.Invoke();
            OnrefreshContent.Raise();
        }

        // Event Handlers
        // Add any event handlers if needed
    }
}